import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/constants/app_spacing.dart';
import '../data/report_service.dart';

class ReportPreviewScreen extends ConsumerWidget {
  const ReportPreviewScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Health Report'),
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            tooltip: 'Share',
            onPressed: () =>
                ref.read(reportServiceProvider).generateAndShare(),
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(AppSpacing.screenPadding),
        children: [
          const _ReportSection(
            title: "What's included",
            content:
                'Last 3 months of cycle dates, period lengths, symptoms, mood patterns, and health metrics.',
          ),
          const SizedBox(height: AppSpacing.md),
          const _ReportSection(
            title: 'Format',
            content: 'PDF document — share via WhatsApp, email, or any app.'
                ' Suitable for healthcare provider visits.',
          ),
          const SizedBox(height: AppSpacing.md),
          const _ReportSection(
            title: 'Disclaimer',
            content:
                'Generated by Ayla. Data is self-reported. This is not a medical document.',
          ),
          const SizedBox(height: AppSpacing.xl),
          FilledButton.icon(
            icon: const Icon(Icons.picture_as_pdf_outlined),
            label: const Text('Generate & Share PDF'),
            onPressed: () =>
                ref.read(reportServiceProvider).generateAndShare(),
          ),
        ],
      ),
    );
  }
}

class _ReportSection extends StatelessWidget {
  const _ReportSection({required this.title, required this.content});
  final String title;
  final String content;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.cardPadding),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title, style: theme.textTheme.titleMedium),
            const SizedBox(height: AppSpacing.xs),
            Text(content, style: theme.textTheme.bodyMedium),
          ],
        ),
      ),
    );
  }
}
