import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../auth/domain/auth_providers.dart';
import '../../cycle/data/cycle_log_repository.dart';
import '../../cycle/domain/cycle_log.dart';
import '../../health/data/health_log_repository.dart';
import '../../health/domain/health_log.dart';
import '../../profile/domain/profile_notifier.dart';

part 'report_service.g.dart';

@riverpod
ReportService reportService(ReportServiceRef ref) {
  return ReportService(ref);
}

class ReportService {
  ReportService(this._ref);

  final ReportServiceRef _ref;

  /// Generates a PDF containing the last 3 months of health data and
  /// triggers the OS share sheet via the [printing] package.
  Future<void> generateAndShare() async {
    final userId = _ref.read(currentUserIdProvider);
    final profile = await _ref.read(profileNotifierProvider.future);

    final now = DateTime.now();
    final from = DateTime(now.year, now.month - 3, now.day);

    final cycleLogs = await _ref
        .read(cycleLogRepositoryProvider)
        .getLogsForRange(userId: userId, from: from, to: now);

    final List<HealthLog> healthLogs = await _ref
        .read(healthLogRepositoryProvider)
        .getLogsForRange(userId: userId, from: from, to: now);

    final doc = _buildDocument(
      profile: (
        cycleLength: profile.cycleLength,
        periodLength: profile.periodLength,
        language: profile.language,
      ),
      cycleLogs: cycleLogs,
      healthLogs: healthLogs,
      from: from,
      to: now,
    );

    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: 'ayla_health_report_${now.year}${_twoDigit(now.month)}${_twoDigit(now.day)}.pdf',
    );
  }

  pw.Document _buildDocument({
    required ({int cycleLength, int periodLength, String language}) profile,
    required List<CycleLog> cycleLogs,
    required List<HealthLog> healthLogs,
    required DateTime from,
    required DateTime to,
  }) {
    final doc = pw.Document();

    // --- Summarise data ---
    final periodDays = cycleLogs
        .where((l) => l.logType == CycleLogType.periodStart)
        .map((l) => l.logDate)
        .toList()
      ..sort();

    final allTypes = cycleLogs.map((l) => l.logType).toList();
    final symptomCounts = <CycleLogType, int>{};
    for (final t in allTypes) {
      if (t == CycleLogType.cramp ||
          t == CycleLogType.headache ||
          t == CycleLogType.bloating) {
        symptomCounts[t] = (symptomCounts[t] ?? 0) + 1;
      }
    }

    final moodCounts = <CycleLogType, int>{};
    for (final t in allTypes) {
      if (t.value.startsWith('mood_')) {
        moodCounts[t] = (moodCounts[t] ?? 0) + 1;
      }
    }

    // --- Build PDF ---
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (_) => _header(from, to),
        footer: (_) => _footer(),
        build: (_) => [
          _sectionTitle('Cycle Summary'),
          _infoRow(
              'Cycle length setting', '${profile.cycleLength} days'),
          _infoRow(
              'Period length setting', '${profile.periodLength} days'),
          _infoRow('Period starts logged', '${periodDays.length}'),
          if (periodDays.isNotEmpty) ...[
            _infoRow('First period start',
                _formatDate(periodDays.first)),
            _infoRow(
                'Last period start', _formatDate(periodDays.last)),
          ],
          pw.SizedBox(height: 16),
          _sectionTitle('Symptoms (last 3 months)'),
          if (symptomCounts.isEmpty)
            _body('No symptoms logged.')
          else
            ...symptomCounts.entries.map(
              (e) => _infoRow(
                _labelFor(e.key),
                '${e.value} time${e.value == 1 ? '' : 's'}',
              ),
            ),
          pw.SizedBox(height: 16),
          _sectionTitle('Mood (last 3 months)'),
          if (moodCounts.isEmpty)
            _body('No mood logs.')
          else
            ...moodCounts.entries.map(
              (e) => _infoRow(
                _labelFor(e.key),
                '${e.value} time${e.value == 1 ? '' : 's'}',
              ),
            ),
          pw.SizedBox(height: 16),
          _sectionTitle('Note for Healthcare Provider'),
          _body(
            'This report was automatically generated by the Ayla app. '
            'It summarises self-reported cycle and health data over the period '
            '${_formatDate(from)} – ${_formatDate(to)}. '
            'This is not a medical document. All data is provided by the patient.',
          ),
        ],
      ),
    );

    return doc;
  }

  // ---------------------------------------------------------------------------
  // PDF widget helpers
  // ---------------------------------------------------------------------------

  pw.Widget _header(DateTime from, DateTime to) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Ayla Health Report',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: PdfColor.fromHex('#7C6FAB'),
              ),
            ),
            pw.Text(
              '${_formatDate(from)} – ${_formatDate(to)}',
              style: pw.TextStyle(
                fontSize: 10,
                color: PdfColor.fromHex('#8A82A0'),
              ),
            ),
          ],
        ),
        pw.Divider(color: PdfColor.fromHex('#E8E4F0')),
        pw.SizedBox(height: 8),
      ],
    );
  }

  pw.Widget _footer() {
    return pw.Column(
      children: [
        pw.Divider(color: PdfColor.fromHex('#E8E4F0')),
        pw.Text(
          'Generated by Ayla · ayla.app · Data is self-reported and not verified.',
          style: pw.TextStyle(
            fontSize: 8,
            color: PdfColor.fromHex('#8A82A0'),
          ),
          textAlign: pw.TextAlign.center,
        ),
      ],
    );
  }

  pw.Widget _sectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: PdfColor.fromHex('#7C6FAB'),
        ),
      ),
    );
  }

  pw.Widget _infoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label,
              style: pw.TextStyle(
                  fontSize: 11, color: PdfColor.fromHex('#2D2640'))),
          pw.Text(value,
              style: pw.TextStyle(
                  fontSize: 11,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#2D2640'))),
        ],
      ),
    );
  }

  pw.Widget _body(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(text,
          style: pw.TextStyle(
              fontSize: 10, color: PdfColor.fromHex('#8A82A0'))),
    );
  }

  // ---------------------------------------------------------------------------

  static String _twoDigit(int n) => n.toString().padLeft(2, '0');

  static String _formatDate(DateTime d) =>
      '${d.day.toString().padLeft(2, '0')} ${_kMonths[d.month]} ${d.year}';

  static const _kMonths = [
    '', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];

  static String _labelFor(CycleLogType t) {
    return t.value.replaceAll('_', ' ').split(' ').map((w) {
      if (w.isEmpty) return w;
      return '${w[0].toUpperCase()}${w.substring(1)}';
    }).join(' ');
  }
}
